spring:
  application:
    name: zeroq-service-back
  profiles:
    active: local
    group:
      local: local
      test: test
      dev: dev
      prod: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    discovery:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: your-super-secret-key-change-this-in-production-12345
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
