log.config.path=/data/logs/dev/auth_back_server
log.config.app.error.name=auth_back_server_dev_app_error
log.config.app.warn.name=auth_back_server_dev_app_warn
log.config.sql.error.name=auth_back_server_dev_sql_error
log.config.sql.trace.name=auth_back_server_dev_sql_trace